spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587

application:
  security:
    jwt:
      secret-key: 
      expiration: 
      refresh-token:
        expiration: 
